# Generated by Django 4.2.9 on 2024-02-01 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
