# Generated by Django 4.2.9 on 2024-02-02 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('exp', models.IntegerField()),
            ],
            options={
                'db_table': 'directors',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('director_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.director')),
                ('title', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('isActive', models.BooleanField(default=True)),
                ('ratings', models.FloatField()),
            ],
            options={
                'db_table': 'movies',
            },
            bases=('blog.director',),
        ),
    ]
